### ISSUE TITLE
User is able to submit half filled Experience form. 

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/dine-safe-ly#170] opened 2020-11-25 17:41 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I am able to submit an incomplete experience form and the data doesn't change if I do that. 

## Expected Behavior

Either the user should not be able to submit an incomplete form
OR
If allowed, the data should reflect in reviews.

## Current Behavior

It lets me submit the form but the data is not reflected under reviews.

## Steps to Reproduce

1. Navigate to restaurants page.
2. Open any restaurant
**Before filling the form**

![image](https://user-images.githubusercontent.com/55005259/100262852-58c2a480-2f12-11eb-8c06-35777db8ab8a.png)

3. Click on 'Have you been here before' button
4. Fill 2 fields as yes and leave everything else blank and submit the form.
![image](https://user-images.githubusercontent.com/55005259/100263003-8f98ba80-2f12-11eb-8872-07e60584c984.png)

5. All the fields are still false
![image](https://user-images.githubusercontent.com/55005259/100263411-164d9780-2f13-11eb-929e-1b5719f9442a.png)

**Comment by gauravag2207** [comment] 2020-11-26 01:25
Hi Edward,

It would be great f you can link the original issue number.

Thanks,
Gaurav

**Comment by Chuanqi927** [comment] 2020-11-26 01:46
duplicate of #177 and #182

**Comment by gauravag2207** [comment] 2020-11-26 01:51
Hi Edward,

Again, If this was raised before #177 and #182, how can this be a duplicate. Those should be a duplicate right?

Thanks,
Gaurav

**Comment by ronakf11** [comment] 2020-11-29 20:30
Hey Gaurav,
Thank you for reporting this to us.
We are currently looking into this issue.

**Closed as completed** 2020-12-03 01:36 UTC
Labels: bug
