### ISSUE TITLE
extra padding for gray star in the rating in the restaurant detail page

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#155] opened 2020-11-24 17:52 UTC
The issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

extra padding on the right for each gray star in the restaurant detail page

## Expected Behavior

The star in the review should be aligned without the right padding

## Current Behavior

extra padding on the right for each gray star in the restaurant detail page

## Ideas for Improvement

remove the padding

## Steps to Reproduce

1. https://dine-safe-ly.herokuapp.com/restaurant/profile/4649/
2. https://dine-safe-ly.herokuapp.com/restaurant/profile/4/
3. https://dine-safe-ly.herokuapp.com/restaurant/profile/2264/
4. https://dine-safe-ly.herokuapp.com/restaurant/profile/4691/

## Context (Environment)

N/A

chrome browser

**Comment by Chuanqi927** [comment] 2020-11-26 01:18
Hello, thanks for pointing this out. We have noticed this and have already fixed this. Will deploy after test party.

**Comment by Chuanqi927** [comment] 2020-11-26 01:44
duplicate of #175

**Closed as completed** 2020-12-03 01:36 UTC
Labels: duplicate, enhancement
