### ISSUE TITLE
Preference is not saving all the selections and none at times

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/dine-safe-ly#168] opened 2020-11-25 04:00 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Select preferences(one or multiple) and all preferences should be saved

## Current Behavior

Select one preference and none is saved. Select multiple, maybe 2 is saved. Behaviour is very random

## Steps to Reproduce

1. Select the first 4 options from the list - New American, Armenian, Bars and Bistro
2. Click on update preferences 
3. Only newamerican and armenian apear
4. The text changes to all lower case without spacing as well

## Context (Environment)

As a user, I would expect my preferences to be saved properly. 
Environment: chrome

**Comment by Chuanqi927** [comment] 2020-11-26 01:16
Hello, when I tried to reproduce this scenario, it did not happen. Can you try it one more time? You can also refresh the page to see. Also, they are converted to lower case because it makes our life easier to store to database. We can change the displaying text for future improvements.

**Comment by i-rahman** [comment] 2020-11-26 02:42
@Edward0o0 Here is a Screen record of the Issue being reproduced. 
https://drive.google.com/file/d/1gurUM-TaYKRQvruVGXqMwIVjsBVL71QZ/view?usp=sharing

Also, as per your suggestion I did refresh the page, even navigated to home page and came back to the profile page. Hope this Clarifies the bug.

**Comment by ronakf11** [comment] 2020-11-29 20:23
Thank you for reporting this to us.
We are currently looking into the same issue in reference to issue #165
So we'll close this one.

**Closed as completed by ronakf11** 2020-11-29 20:23 UTC
Labels: duplicate
