### ISSUE TITLE
Users can submit empty or incomplete 'Have you been here before forms'

### ISSUE THREAD

**Issue by joshganguly** [gcivil-nyu-org/dine-safe-ly#177] opened 2020-11-25 21:35 UTC
Users can submit empty 'Have you been here before forms' and the 'MOST RECENT USER FEEDBACK' section does not handle this

## Expected Behavior
Users should not be able to submit empty or incomplete form

## Current Behavior
Users can submit empty forms and the 'MOST RECENT USER FEEDBACK' section does not handle this

## Steps to Reproduce
1. Go to a restaurant like `https://dine-safe-ly.herokuapp.com/restaurant/profile/4753/`
2. Click 'Have you been here before forms'
3. Submit the form without filling in any data or filling in incomplete data
4. Then check the 'MOST RECENT USER FEEDBACK' section to see it does not change

## Context (Environment)
By allowing Users to submit empty or incomplete forms (and not handling it in the 'MOST RECENT USER FEEDBACK' where one expects to see the results) it defeats the purpose of the form.

**Comment by Chuanqi927** [comment] 2020-11-26 00:39
Hello, thanks for pointing this out. You are right, currently we do not allow user to submit incomplete form, but we did not notify user that they are not allowed to do. In other words, you can click on submit if you do not complete all the fields, but nothing will happen. We will improve this by poping up notifcation to user saying all fields are required.

**Comment by Chuanqi927** [comment] 2020-11-26 01:42
duplicate of #182 and #170

**Comment by ronakf11** [comment] 2020-11-29 20:40
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #170

**Closed as completed by ronakf11** 2020-11-29 20:40 UTC
Labels: duplicate
