### ISSUE TITLE
UI icons mislead user into thinking he/she is clicking button

### ISSUE THREAD

**Issue by joshganguly** [gcivil-nyu-org/dine-safe-ly#178] opened 2020-11-25 22:20 UTC
UI icons mislead user into thinking he/she is clicking button (Also it says 1.5 reviews instead of 1.5 ratings score)

## Expected Behavior
UI CSS icons should not lead user into expecting some action will be taken if he/she clicks it

## Current Behavior
UI icons mislead user into thinking he/she is clicking button. For example the 'Phone' or 'Star' icons on `https://dine-safe-ly.herokuapp.com/restaurant/profile/4753/` act as unclickable buttons - 

![Screen Shot 2020-11-25 at 4 47 06 PM](https://user-images.githubusercontent.com/12211050/100287357-7d367500-2f42-11eb-8368-a055949ce7c5.png)

## Ideas for Improvement
Add an action URL for the button or remove the a href tag for buttons that don't need to be clicked

## Steps to Reproduce
1. Go to `https://dine-safe-ly.herokuapp.com/restaurant/profile/4753/` and click on the mentioned buttons

## Context (Environment)
User can be mislead into thinking he/she is clicking button and that some action might be taken

**Comment by Chuanqi927** [comment] 2020-11-26 00:46
Hello, thanks for pointing that out. We have noticed this and will certainly improve it in the future. Right now we did not implement the action for these buttons. We will decide either implementing those or disabling the button.

**Comment by Chuanqi927** [comment] 2020-11-26 01:42
duplicate of #174

**Comment by ronakf11** [comment] 2020-11-29 20:41
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #162

**Closed as completed by ronakf11** 2020-11-29 20:41 UTC
Labels: duplicate
