### ISSUE TITLE
Clicking on any item under "Information" on restaurant page scrolls to top of the page

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/dine-safe-ly#174] opened 2020-11-25 18:21 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Clicking on any item under "Information" on a restaurant page scrolls to the top of the page

## Expected Behavior

It should not be clickable if it's just information.

## Current Behavior

Scrolls to the top of the page

## Ideas for Improvement

Remove the href attr from the <a> tag

## Steps to Reproduce

1. Navigate to Any restaurant's page
2. Click on Phone Number or reviews or cost under 'Information'
![image](https://user-images.githubusercontent.com/55005259/100267259-c96cbf80-2f18-11eb-8b6f-d5da484cc66e.png)

3. You would be scrolled to the top

**Comment by gauravag2207** [comment] 2020-11-25 21:46
Sorry, I didn't mean to open a duplicate one but I did not see a duplicate so opened it.

**Comment by Chuanqi927** [comment] 2020-11-26 00:45
Hello, thanks for pointing that out. We have noticed this and will certainly improve it in the future. Right now we did not implement the action for these buttons. We will decide either implementing those or disabling the button.

**Comment by Chuanqi927** [comment] 2020-11-26 01:44
duplicate of #178

**Comment by gauravag2207** [comment] 2020-11-26 01:46
Hi Edward,

If this was raised before #178, how can this be a duplicate. That should be a duplicate right?

Thanks,
Gaurav

**Comment by Chuanqi927** [comment] 2020-11-26 01:52
Please do not mind. It will make our life eaiser to mark all of them as duplicates when we tried to resolve the issues... It will not affect your contribution becuase TA and Prof will know the time of submission.

**Comment by gauravag2207** [comment] 2020-11-26 01:56
Hi @Edward0o0 ,

I don't mind at all. It was just the process that I am aware of was pushing me. But no worries. I am good with what you guys are comfortable with. Great app btw. One of the best UI of all.

Thanks,
Gaurav

**Comment by ronakf11** [comment] 2020-11-29 20:37
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #162

**Closed as completed by ronakf11** 2020-11-29 20:37 UTC
Labels: duplicate, enhancement
